tests:
    name: pytest tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.1.0
      - name: Python Pylin GitHub Action
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pip3 install -r requirements.txt && pytest test/unit